# .github/workflows/aws.yml
name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Gunicorn
      run: |
        pip install gunicorn

    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}

    - name: Deploy to AWS Elastic Beanstalk
      run: |
        eb init -p python-3.8 your-app-name
        eb create your-environment-name

    - name: Check AWS Elastic Beanstalk environment status
      run: |
        STATUS=$(aws elasticbeanstalk describe-environments --environment-names your-environment-name --query "Environments[0].Status" --output text)
        if [ "$STATUS" == "Ready" ]; then
          echo "Deployment successful. Environment is ready."
        else
          echo "Deployment failed. Environment status: $STATUS"
          exit 1
        fi

    - name: Start Gunicorn server
      run: |
        gunicorn -b 0.0.0.0:5000 app:app
