# .github/workflows/python-app.yml
name: Python App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests (replace with your actual test command)
      run: |
        python -m unittest discover -s tests

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Deployment
      run: |
        python app.py

      # ... (previous steps)
    # ... (previous steps)
    - name: Check AWS Elastic Beanstalk environment status
      run: |
        STATUS=$(aws elasticbeanstalk describe-environments --environment-names your-environment-name --query "Environments[0].Status" --output text)
        if [ "$STATUS" == "Ready" ]; then
          echo "Deployment successful. Environment is ready."
        else
          echo "Deployment failed. Environment status: $STATUS"
          exit 1
        fi

    - name: Start Gunicorn server
        run: |
        gunicorn -b 0.0.0.0:5000 wsgi:app


